### ISSUE TITLE
Deprecated Dev Dependencies 

### ISSUE THREAD

**Issue by ackushiw** [mcfly-io/generator-mcfly#277]
When installing the generator I get these npm warnings
```
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
```

**Comment by thaiat** [comment]
i have tried to install the latest, i know i ve seen those warnings in the past, but i don't get them anymore.
Any idea what package is causing that ?

**Comment by thaiat** [comment]
ok forget my last comment.
I was using the generator to scaffold a project not installing the generator itself...

Anyway, these warnings come from the version of yeoman we are using. The problem is i can't upgrade right now as the new version is causing issue and i didn't have enough time to look into that.

Maybe this is something you could help with ?

**Comment by ackushiw** [comment]
I'm not familiar with building yeoman generators. I'll do some research.

**Comment by thaiat** [comment]
closing this for the moment, feel free to reopen
