### ISSUE TITLE
Gulp webpack:run can't find entry point

### ISSUE THREAD

**Issue by realisation** [mcfly-io/generator-mcfly#312]
I just set up a project as described, and got this error when trying to run `gulp webpack:run`...

`ERROR in Entry module not found: Error: Cannot resolve 'file' or 'directory' ./main.js`

**Comment by thaiat** [comment]
you should change the value of `moduleManager` in `gulp_tasks/common/constants.js`
also instead of running `gulp webpack:run` just run higher level commands such as 
* `gulp browsersync`
* `gulp dist`
* etc...
depending on what you want to do.

closing this for now, let me know if you need to reopen
